name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1']

    env:
      BUNDLE_WITHOUT: development

    steps:
    - name: repository checkout
      uses: actions/checkout@v2

    - name: set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: run rspec
      run: bundle exec rspec
